### PR TITLE
Conform to PEP8 rules

### PR DESCRIPTION
**Pull request by edawine**
Changes '%' string format to '.format'
Removes any stray whitespace
Uses single quotes instead of double quotes to remove double quotes
escapes

### CODE REVIEW

**Comment by edawine** [comment]
I've done the travis-ci build, and it failed because it takes too long (>10 minutes) at the last test-data (live-2016-04-11). Otherwise, it's working fine.

**Comment by nthykier** [comment]
Thanks for writing a patch for Britney2 :)

Do you have any experience with setting up a test to ensure the code conforms to pep8?  Without active enforcement, I fear the codebase will just "de-generate" again, so I prefer having a test case to catch regressions.

Note that I am working on setting up unit tests using nosetests (see the "britney-patch-bundle-next" branch). If the pep8 enforcement could fit within that, then it would be awesome. :)

Re: live-data tests timing out - That is a known issue.  It occurs every now and then.  I hope to eventually get around and fix the test runnner (which is also very unhelpful on test failures on travis).

**Comment by edawine** [comment]
I'm sorry I can't help you yet with setting up a test for pep8 because I'm still very new in this.

About the live-data tests, travis-ci suggests using travis_wait to extend the output waiting time to 20 minutes (see https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received), so maybe you can use that to at least 'silence' the problem for now? I tried to do it in my fork, but I still haven't understand what to do.

**Comment by nthykier** [comment]
I think I fixed the test runner - at least I got a very promising build with continuous output from the underlying process.  At the same time, it should also tail the logs on crashes. :) Thanks for (indirectly) nagging me into getting that fixed! :+1: 

As for the branch itself: I appreciate the idea.  However, I will hold of merging this until we figure out how to do pep8 testing at build time. This kind of clean up is generally fairly intrusive and will cause a lot merge conflicts when rebasing/merging (my local) branches. If we do not have enforcement of these style things, we are doomed to repeat this cycle of "style fix / branch breakage", which seems counter productive.

**Comment by nthykier** [comment]
Ok, found some bits in pycodestyle (formerly known as "pep8"): https://pycodestyle.readthedocs.io/en/latest/advanced.html#automated-tests

It mentions nose tests as well, so it looks promising.  Lets see if it can fit into the nose tests on the "britney-patch-bundle-next" branch

**Pull request closed without merging**
